services:
  web:
    image: judethegemini/railsapp:v2
    environment:
      - username=user
      - password=password
      - RAILS_ENV=development
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_db
    ports:
      - "5432:5432"
