apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: judethegemini/railsapp:v13
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres.default.svc.cluster.local
            - name: DATABASE_USERNAME
              value: myuser
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rails-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: rails-secret
